version: '3'
services: 
  aircat-srv:
    build: ./aircat-srv
    container_name: aircat-srv
    ports: 
      - "8080:8080"
      - "9000:9000"
  influxdb:
    image: influxdb
    container_name: influxdb
    environment: 
      INFLUXDB_DB: "aircat"
    volumes: 
      - ./influxdb:/var/lib/influxdb
    ports:
      - "127.0.0.1:8086:8086"      
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes: 
      - ./grafana/provisioning:/etc/grafana/provisioning/
    ports: 
      - "3000:3000"
    